spring:
  application:
    name: kriss917
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/pets
  jpa:
    generate-ddl: false
    show-sql: true

