CREATE TABLE owner
(
    owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    name     VARCHAR(255),
    address  VARCHAR(255),
    CONSTRAINT pk_owner PRIMARY KEY (owner_id)
);

CREATE TABLE pet
(
    pet_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT,
    pet_name VARCHAR(255),
    pet_type VARCHAR(255),
    age      VARCHAR(255),
    CONSTRAINT pk_pet PRIMARY KEY (pet_id)
);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owner (owner_id);