CREATE TABLE IF NOT EXISTS owner
(
    owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    name     VARCHAR(255),
    address  VARCHAR(255),
    CONSTRAINT pk_owner PRIMARY KEY (owner_id)
);

CREATE TABLE IF NOT EXISTS pet
(
    pet_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT,
    pet_name VARCHAR(255),
    pet_type VARCHAR(255),
    age      BIGINT,
    CONSTRAINT pk_pet PRIMARY KEY (pet_id)
);

CREATE TABLE IF NOT EXISTS staff
(
    staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    staff_name VARCHAR(255),
    staff_position VARCHAR(255),
    staff_email VARCHAR(255),
    treatment_id BIGINT,
    CONSTRAINT pk_staff PRIMARY KEY (staff_id)
);